### ISSUE TITLE
current status of this role

### ISSUE THREAD

**Issue by DO1JLR** [hadret/ansible-role-restic#2]
Hello there!

What is the current status of this ansible role?

The last commit was just a few days ago. And also the restic version used is not quite the same as the current [Release](https://github.com/restic/restic/releases/tag/v0.10.0).

How does it look like? Is it still maintained here?

**Comment by hadret** [comment]
Hi 👋 

Yeah, it's still maintained and actively used in production. I try to bump it up every now and then, but there are not a lot of features that need to be introduced. I just fixed CI, some minor bugs and bump the restic_version to 0.9.6. I still need to go through 0.10.0 changelog to see whether there are any changes we would like to incorporate or that are breaking the current setup.

I'm also open for PRs 😉

**Comment by DO1JLR** [comment]
cool. Thanks for the quick answer.

Well, I will have a closer look at the reel and will contact you if I notice anything that could be improved or if I am not sure how to use it. :heart:
