### ISSUE TITLE
Run pre and post script before and after restic

### ISSUE THREAD

**Issue by nununo** [hadret/ansible-role-restic#4]
More often than not, before running restic, some services/containers/etc must be stopped, to make sure that the data being backed up will be consistent.

It would be interesting if, instead of calling `restic` directly, `cron`would call a smart wrapper script which would be able to run pre and post tasks that would respectively stop and restart services using the data being backed up.

**Comment by nununo** [comment]
If you think this idea doesn't go against the philosophy of your role, I can try to think of a way to implement this without introducing much complexity.

Please let me know what you think @hadret.

And... thank you for the role ;)

**Comment by nununo** [comment]
Also, one must consider the security aspects. I'm not an expert in that subject so whatever I come up with... someone will have to make sure it doesn't introduce any vulnerability.

**Comment by hadret** [comment]
@nununo this sounds like a really good idea. Wrapper script is pretty much in place already at that stage so it makes sense to extend it for handling pre/post tasks 👍🏻
