### ISSUE TITLE
Installed restic cannot run without sudo

### ISSUE THREAD

**Issue by nununo** [hadret/ansible-role-restic#5]
Hello,

As far as I could understand, when I use this role to install `restic`, I can only run in with `sudo`. Do you confirm? Or am I doing something wrong?

If this is so, would it be possible to adapt the role to make `restic` available to any user?
Otherwise I won't be able to use it 😞 .

Thanks in advance,
Nuno

**Comment by hadret** [comment]
Hi :wave:

What do you mean by "only run in with `sudo`"? You can run it with any user on the system and you can also specify the user that is allowed to use restic via `restic_user` parameter. What's your use case and what doesn't work as expected?

**Comment by nununo** [comment]
Ops. I'm sorry. You're absolutely right and that solved my issue. Note to self RTFD TWICE!

Sorry for wasting your time!
